name: Update Work Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get contributions via GraphQL
        run: |
          curl -H "Authorization: bearer ${{ secrets.LEEJUNGJUN96_GH_TOKEN }}" \
               -X POST -d '{ "query": "query { user(login:\"leejungjun96\"){ contributionsCollection { contributionCalendar { weeks { contributionDays { color contributionCount date } } } } } }" }' \
               https://api.github.com/graphql > contributions.json

      - name: Convert JSON to SVG
        run: |
          python3 - <<'EOF'
          import json
          data = json.load(open("contributions.json"))
          # TODO: JSON → SVG 변환 로직 (직접 작성 or 오픈소스 사용)
          # 여기서 contributions.svg 생성
          EOF

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add contributions.svg
          git commit -m "Update contributions chart" || echo "No changes"
          git push
