name: Update Work Contributions

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 자정 실행
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch contributions via GraphQL
        run: |
          curl -s -H "Authorization: bearer ${{ secrets.LEEJUNGJUN96_GH_TOKEN }}" \
               -X POST -d '{ "query": "query { user(login:\"leejungjun96\"){ contributionsCollection { contributionCalendar { totalContributions weeks { contributionDays { date contributionCount color } } } } } }" }' \
               https://api.github.com/graphql > contributions.json

      - name: Convert JSON to SVG (Contribution Heatmap)
        run: |
          python3 - <<'EOF'
          import json

          # JSON 불러오기
          with open("contributions.json") as f:
              data = json.load(f)

          weeks = data["data"]["user"]["contributionsCollection"]["contributionCalendar"]["weeks"]

          # SVG 기본 크기 계산 (주 단위로 가로 확장)
          cell_size = 12
          width = len(weeks) * cell_size
          height = 7 * cell_size

          svg = [
              f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
              '<style>rect{shape-rendering:crispEdges;}</style>'
          ]

          # 주별 기여도 색상 박스 찍기
          for x, week in enumerate(weeks):
              for y, day in enumerate(week["contributionDays"]):
                  color = day["color"]
                  svg.append(f'<rect x="{x*cell_size}" y="{y*cell_size}" width="{cell_size}" height="{cell_size}" fill="{color}" />')

          svg.append("</svg>")

          with open("contributions.svg", "w") as f:
              f.write("\n".join(svg))
          EOF

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add contributions.svg
          git commit -m "Update contributions chart" || echo "No changes"
          git push
