name: Update Work Contributions

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 자정 실행
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate contributions chart
        run: |
          npx github-contributions-chart leejungjun96 \
            --token ${{ secrets.LEEJUNGJUN96_GH_TOKEN }} \
            -o contributions.svg

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add contributions.svg
          git commit -m "Update contributions chart"
          git push