name: Update Work Contributions

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 자정 실행
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch contributions via GraphQL
        run: |
          curl -H "Authorization: bearer ${{ secrets.LEEJUNGJUN96_GH_TOKEN }}" \
               -X POST -d '{ "query": "query { user(login:\"leejungjun96\"){ contributionsCollection { contributionCalendar { weeks { contributionDays { contributionCount date } } } } } }" }' \
               https://api.github.com/graphql > contributions.json

      - name: Convert JSON to SVG (Contribution Heatmap)
        run: |
          mkdir -p .github/contributions
          python3 - <<'EOF'
          import json, os

          with open("contributions.json") as f:
              data = json.load(f)

          weeks = data["data"]["user"]["contributionsCollection"]["contributionCalendar"]["weeks"]

          cell_size = 12
          padding = 2
          width = len(weeks) * (cell_size + padding)
          height = 7 * (cell_size + padding)

          svg = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">']

          colors = ["#ebedf0", "#c6e48b", "#7bc96f", "#239a3b", "#196127"]

          for x, week in enumerate(weeks):
              for y, day in enumerate(week["contributionDays"]):
                  count = day["contributionCount"]
                  if count == 0:
                      color = colors[0]
                  elif count < 3:
                      color = colors[1]
                  elif count < 6:
                      color = colors[2]
                  elif count < 10:
                      color = colors[3]
                  else:
                      color = colors[4]
                  svg.append(
                      f'<rect x="{x*(cell_size+padding)}" y="{y*(cell_size+padding)}" width="{cell_size}" height="{cell_size}" fill="{color}"/>'
                  )

          svg.append("</svg>")

          os.makedirs(".github/contributions", exist_ok=True)
          with open(".github/contributions/work_account.svg", "w") as f:
              f.write("\n".join(svg))
          EOF

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/contributions/work_account.svg
          git commit -m "Update work contributions chart" || echo "No changes"
          git push
